title: <p align="center"> Valentina Osses </p>

description:
 
  <p align="justify">
  Estudiante de Ingenieria Civil Matemática en la Universidad de la Frontera, Chile.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
